"""empty message

Revision ID: 7207debb4f18
Revises: 0ff75771865f
Create Date: 2023-09-05 15:27:04.472338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7207debb4f18'
down_revision = '0ff75771865f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('update_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.drop_column('update_time')
        batch_op.drop_column('create_time')

    # ### end Alembic commands ###
